### ISSUE TITLE
gtk_sheet_put () issue in gtksheet

### ISSUE THREAD

**Issue by songqingshan** [fpaquet/gtksheet#29] opened 2020-09-22 01:49 UTC
Gtk-WARNING **: 22:29:03.191: Can't set a parent on widget which has a parent

**Comment by fpaquet** [comment] 2021-02-09 18:18
Do you have more details?

**Comment by songqingshan** [comment] 2021-02-14 15:31
my stack trace only provides those information.
Thanks for your work.

________________________________

**Comment by fpaquet** [comment] 2021-02-16 07:42
We're closing this issue due to lack of information.
Not reproducible.

**Closed by fpaquet** 2021-02-16 07:42 UTC
