### ISSUE TITLE
gtk_sheet_button_attach can not attach a button.

### ISSUE THREAD

**Issue by songqingshan** [fpaquet/gtksheet#12] opened 2018-12-21 16:59 UTC
I have reported attaching button issue using gtk_sheet_attach function in the issue 1.  gtk_sheet_attach can attach a button, but when revisiting the same page, the button disappears and sometimes testgtksheet crashes. 
 when I use gtk_sheet_button_attach to attach a button in my test sheet, the button never shows and no warning or error message. When clicking the button cell, the message "GLib-CRITICAL **: 11:40:42.929: Source ID 7392 was not found when attempting to remove it". Callback function never works.

**Comment by fpaquet** [comment] 2019-03-03 17:24
Which branch are you using?

**Comment by fpaquet** [comment] 2019-03-09 11:38
I've now released V4.3.0 for Gtk3 (branch gtk3)
https://github.com/fpaquet/gtksheet/releases/tag/V4.3.0

And published online docs V4
https://fpaquet.github.io/gtksheet/reference/index.html

This should fix the missing button issue.

**Comment by fpaquet** [comment] 2019-03-10 11:00
The timer issue was fixed in commit 6620015 in branch gtk3_fixes
Thank you for reporting.

**Comment by fpaquet** [comment] 2019-03-10 11:02
example1 in testgtksheet.c(835) shows a working example with show_button callback.

**Comment by songqingshan** [comment] 2019-03-12 04:31
Hello Fredy,
Thank your fixing some issues in 4.2.0 and releasing 4.3.0.
I try the 4.3.0 and attached is the screen output of testgtksheet.exe.
issue 1
(testgtksheet.exe:2816): Gtk-CRITICAL **: 23:44:30.140: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed.
this issues exists in both 4.2.0 and 4.3.0. I know this issue in 4.2.0, but I have not reported it.
issue 2

(testgtksheet.exe:2816): GLib-CRITICAL **: 23:44:37.279: Source ID 634 was not found when attempting to remove it

I believe that is caused by mapping as I mentioned before. It is highly caused by matrix button (top-left button or button "0"). In other words, mapping issue is partially resolved as I told.


issue 3

(testgtksheet.exe:2816): Gtk-CRITICAL **: 23:44:48.461: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton
This issue exists in both 4.2.0 and 4.3.0

I hope you can take time to look at them.

Song
  *



________________________________

**Comment by fpaquet** [comment] 2019-03-17 09:30
issue 1 - already fixed in gtk3_fixes branch
issue 2 - already fixed in gtk3_fixes branch
issue 3 - can be reproduced here

**Comment by fpaquet** [comment] 2019-03-17 11:30
issue 3
> Gtk-CRITICAL **: 23:44:48.461: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

This must be an upstream bug in GtkSpinButton. No matter what size we give to the spin button, this warning always appears on the next spin button activation. If we give it 150 pixels, it requires 181 pixels. If we give it 300 pixels, it requires 331 pixels. CSS doesn't seam to have any related properties.

Because this doesn't affect correct drawing of the spin button, i will close this issue.

**Closed by fpaquet** 2019-03-17 11:30 UTC

**Comment by fpaquet** [comment] 2019-03-17 12:12
I found out, that setting the width-chars property of the spin button entry to 0 helps.
This is now done automatically (branch gtk3-fixes, not yet released)
