### ISSUE TITLE
Segmentation fault in gtk_sheet_position_child ()

### ISSUE THREAD

**Issue by songqingshan** [fpaquet/gtksheet#31] opened 2020-10-02 04:58 UTC
Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000006fb5b8ed in gtk_sheet_position_child ()
   from C:\msys64\mingw64\bin\libgtksheet-4.0-1.dll

**Comment by fpaquet** [comment] 2021-02-09 18:17
Can you produce a stack trace?

**Comment by songqingshan** [comment] 2021-02-14 15:29
Hello,
Thanks for your response.
Attached is only a stack trace, which you already have. I cannot produce more.

________________________________

**Comment by fpaquet** [comment] 2021-02-16 07:41
We're closing this issue due to lack of information.
Not reproducible.

**Closed by fpaquet** 2021-02-16 07:41 UTC
